import { type Mermaid } from "mermaid";
import { Pantsdown } from "pantsdown";
import { useContext, useEffect, useState } from "react";
import { cn, getFileExt } from "../../utils.ts";
import { websocketContext } from "../websocket-provider/context.ts";
import { BreadCrumbs } from "./breadcrumbs.tsx";
import { CURSOR_LINE_ELEMENT_ID, CursorLine } from "./cursor-line.tsx";
import { LINE_NUMBERS_ELEMENT_ID, LineNumbers } from "./line-numbers.tsx";
import { getScrollOffsets, type Offsets } from "./scroll.ts";

const MARKDOWN_CONTAINER_ID = "markdown-container-id";
const MARKDOWN_ELEMENT_ID = "markdown-element-id";

declare const mermaid: Mermaid;

async function runMermaid() {
    await mermaid.run({
        querySelector: ".mermaid",
        suppressErrors: true,
        postRenderCallback(_id) {
            // console.log("id: ", id);
        },
    });
}

export const Markdown = ({ className }: { className: string }) => {
    const { config, registerHandler, wsRequest } = useContext(websocketContext);
    const [offsets, setOffsets] = useState<Offsets>([]);
    const [pantsdown, setPantsdown] = useState(
        new Pantsdown({
            renderer: {
                relativeImageUrlPrefix: "/__github_preview__/image/",
                detailsTagDefaultOpen: config?.overrides.details_tags_open ?? true,
            },
        }),
    );
    // const mermaids = useRef<Record<string, string>>({});

    const [markdownElement, setMarkdownElement] = useState<HTMLElement>();
    const [cursorLineElement, setCursorLineElement] = useState<HTMLElement>();
    const [lineNumbersElement, setLineNumbersElement] = useState<HTMLElement>();
    const [markdownContainerElement, setMarkdownContainerElement] = useState<HTMLElement>();

    const details_tags_open = config?.overrides.details_tags_open;
    const single_file = config?.overrides.single_file;

    useEffect(() => {
        if (details_tags_open === undefined) return;
        setPantsdown(
            new Pantsdown({
                renderer: {
                    relativeImageUrlPrefix: "/__github_preview__/image/",
                    detailsTagDefaultOpen: details_tags_open,
                },
            }),
        );
    }, [details_tags_open]);

    useEffect(() => {
        setMarkdownElement(document.getElementById(MARKDOWN_ELEMENT_ID)!);
        setCursorLineElement(document.getElementById(CURSOR_LINE_ELEMENT_ID)!);
        setLineNumbersElement(document.getElementById(LINE_NUMBERS_ELEMENT_ID)!);
        setMarkdownContainerElement(document.getElementById(MARKDOWN_CONTAINER_ID)!);
    }, []);

    useEffect(() => {
        if (!markdownElement || !cursorLineElement || !lineNumbersElement) return;
        // const serializer = new XMLSerializer();

        registerHandler("markdown", async (message) => {
            if ("lines" in message) {
                const fileExt = getFileExt(message.currentPath);

                const text = message.lines.join("\n");
                const markdown = fileExt === "md" ? text : "```" + fileExt + `\n${text}`;
                markdownElement.innerHTML = pantsdown.parse(markdown);

                // We find the code-copy <script> generated by pantsdown
                // and create a new <script> element to be appended
                // to the document or else the script is not executed
                const script: HTMLScriptElement =
                    markdownElement.querySelector("#code-copy-script")!;
                const newScript = document.createElement("script");
                newScript.text = script.innerText;
                markdownElement.appendChild(newScript);

                markdownElement.querySelectorAll("a").forEach((element) => {
                    element.addEventListener("click", (event) => {
                        const href = (event.currentTarget as HTMLAnchorElement).href;
                        const base = window.location.origin + "/";

                        // if absolute path, let it allow default behaviour
                        if (!href.startsWith(base)) return;

                        // update path otherwise
                        event.preventDefault();
                        const pathname = href.slice(base.length);
                        wsRequest({ type: "get-entry", path: pathname });
                    });
                });

                if (fileExt === "md") {
                    markdownElement.style.setProperty("padding", "44px");
                    markdownElement.style.setProperty("max-width", "1012px");
                    cursorLineElement.style.removeProperty("transform");
                    lineNumbersElement.style.setProperty("display", "none");
                } else {
                    // rendering code file
                    markdownElement.style.setProperty("padding", "20px 0 0 60px");
                    markdownElement.style.removeProperty("max-width");
                    // move cursorLineElement up so line of code is vertically centered
                    cursorLineElement.style.setProperty("transform", "translateY(-9px)");
                    lineNumbersElement.style.setProperty(
                        "display",
                        message.lines.length ? "block" : "none",
                    );

                    // Change code background color to canvas default when displaying only code
                    const codeContainer = markdownElement.getElementsByTagName("pre")[0];
                    if (codeContainer) {
                        codeContainer.style.setProperty("padding", "0px 16px");
                        codeContainer.style.setProperty(
                            "background",
                            "var(--color-canvas-default)",
                        );
                    }
                }

                await runMermaid();
            }
        });
    }, [
        registerHandler,
        wsRequest,
        single_file,
        pantsdown,
        markdownElement,
        cursorLineElement,
        lineNumbersElement,
    ]);

    useEffect(() => {
        // recalculate offsets whenever markdownElement's height changes
        if (!markdownElement || !markdownContainerElement) return;

        const observer = new ResizeObserver(() => {
            setOffsets(getScrollOffsets(markdownContainerElement, markdownElement));
        });

        observer.observe(markdownElement);

        return () => {
            observer.disconnect();
        };
    }, [markdownElement, markdownContainerElement]);

    return (
        <div
            className={cn(
                "relative box-border rounded border",
                "border-github-border-default bg-github-canvas-default",
                className,
            )}
            id={MARKDOWN_CONTAINER_ID}
        >
            <BreadCrumbs />
            <CursorLine
                offsets={offsets}
                cursorLineElement={cursorLineElement}
                markdownContainerElement={markdownContainerElement}
            />
            <div id={MARKDOWN_ELEMENT_ID} className="relative mx-auto mb-96" />
            <LineNumbers offsets={offsets} lineNumbersElement={lineNumbersElement} />
        </div>
    );
};
