// filter deprecated

export const apiInfo = {
    version: {
        major: 0,
        minor: 9,
        patch: 1,
        prerelease: false,
        api_level: 11,
        api_compatible: 0,
        api_prerelease: false,
    },
    functions: [
        {
            name: "nvim_get_autocmds",
            since: 9,
            parameters: [["Dictionary", "opts"]],
            return_type: "Array",
            method: false,
        },
        {
            name: "nvim_create_autocmd",
            since: 9,
            parameters: [
                ["Object", "event"],
                ["Dictionary", "opts"],
            ],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_del_autocmd",
            since: 9,
            parameters: [["Integer", "id"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_clear_autocmds",
            since: 9,
            parameters: [["Dictionary", "opts"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_create_augroup",
            since: 9,
            parameters: [
                ["String", "name"],
                ["Dictionary", "opts"],
            ],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_del_augroup_by_id",
            since: 9,
            parameters: [["Integer", "id"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_del_augroup_by_name",
            since: 9,
            parameters: [["String", "name"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_exec_autocmds",
            since: 9,
            parameters: [
                ["Object", "event"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_buf_line_count",
            since: 1,
            parameters: [["Buffer", "buffer"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_buf_attach",
            since: 4,
            parameters: [
                ["Buffer", "buffer"],
                ["Boolean", "send_buffer"],
                ["Dictionary", "opts"],
            ],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_buf_detach",
            since: 4,
            parameters: [["Buffer", "buffer"]],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_buf_get_lines",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start"],
                ["Integer", "end"],
                ["Boolean", "strict_indexing"],
            ],
            return_type: "ArrayOf(String)",
            method: true,
        },
        {
            name: "nvim_buf_set_lines",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start"],
                ["Integer", "end"],
                ["Boolean", "strict_indexing"],
                ["ArrayOf(String)", "replacement"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_set_text",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start_row"],
                ["Integer", "start_col"],
                ["Integer", "end_row"],
                ["Integer", "end_col"],
                ["ArrayOf(String)", "replacement"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_get_text",
            since: 9,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start_row"],
                ["Integer", "start_col"],
                ["Integer", "end_row"],
                ["Integer", "end_col"],
                ["Dictionary", "opts"],
            ],
            return_type: "ArrayOf(String)",
            method: true,
        },
        {
            name: "nvim_buf_get_offset",
            since: 5,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "index"],
            ],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_buf_get_var",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "nvim_buf_get_changedtick",
            since: 2,
            parameters: [["Buffer", "buffer"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_buf_get_keymap",
            since: 3,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "mode"],
            ],
            return_type: "ArrayOf(Dictionary)",
            method: true,
        },
        {
            name: "nvim_buf_set_keymap",
            since: 6,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "mode"],
                ["String", "lhs"],
                ["String", "rhs"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_del_keymap",
            since: 6,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "mode"],
                ["String", "lhs"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_set_var",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_del_var",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_get_name",
            since: 1,
            parameters: [["Buffer", "buffer"]],
            return_type: "String",
            method: true,
        },
        {
            name: "nvim_buf_set_name",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_is_loaded",
            since: 5,
            parameters: [["Buffer", "buffer"]],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_buf_delete",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_is_valid",
            since: 1,
            parameters: [["Buffer", "buffer"]],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_buf_del_mark",
            since: 8,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_buf_set_mark",
            since: 8,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
                ["Integer", "line"],
                ["Integer", "col"],
                ["Dictionary", "opts"],
            ],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_buf_get_mark",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "ArrayOf(Integer, 2)",
            method: true,
        },
        {
            name: "nvim_buf_call",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["LuaRef", "fun"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "nvim_parse_cmd",
            since: 10,
            parameters: [
                ["String", "str"],
                ["Dictionary", "opts"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_cmd",
            since: 10,
            parameters: [
                ["Dictionary", "cmd"],
                ["Dictionary", "opts"],
            ],
            return_type: "String",
            method: false,
        },
        {
            name: "nvim_create_user_command",
            since: 9,
            parameters: [
                ["String", "name"],
                ["Object", "command"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_del_user_command",
            since: 9,
            parameters: [["String", "name"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_buf_create_user_command",
            since: 9,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
                ["Object", "command"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_del_user_command",
            since: 9,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_get_commands",
            since: 4,
            parameters: [["Dictionary", "opts"]],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_buf_get_commands",
            since: 4,
            parameters: [
                ["Buffer", "buffer"],
                ["Dictionary", "opts"],
            ],
            return_type: "Dictionary",
            method: true,
        },
        {
            name: "nvim_exec",
            deprecated_since: 11,
            since: 7,
            parameters: [
                ["String", "src"],
                ["Boolean", "output"],
            ],
            return_type: "String",
            method: false,
        },
        {
            name: "nvim_command_output",
            deprecated_since: 7,
            since: 1,
            parameters: [["String", "command"]],
            return_type: "String",
            method: false,
        },
        {
            name: "nvim_execute_lua",
            deprecated_since: 7,
            since: 3,
            parameters: [
                ["String", "code"],
                ["Array", "args"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_buf_get_number",
            deprecated_since: 2,
            since: 1,
            parameters: [["Buffer", "buffer"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_buf_clear_highlight",
            deprecated_since: 7,
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["Integer", "line_start"],
                ["Integer", "line_end"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_buf_set_virtual_text",
            deprecated_since: 8,
            since: 5,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "src_id"],
                ["Integer", "line"],
                ["Array", "chunks"],
                ["Dictionary", "opts"],
            ],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_get_hl_by_id",
            deprecated_since: 9,
            since: 3,
            parameters: [
                ["Integer", "hl_id"],
                ["Boolean", "rgb"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_get_hl_by_name",
            deprecated_since: 9,
            since: 3,
            parameters: [
                ["String", "name"],
                ["Boolean", "rgb"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "buffer_insert",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "lnum"],
                ["ArrayOf(String)", "lines"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "buffer_get_line",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "index"],
            ],
            return_type: "String",
            method: false,
        },
        {
            name: "buffer_set_line",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "index"],
                ["String", "line"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "buffer_del_line",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "index"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "buffer_get_line_slice",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start"],
                ["Integer", "end"],
                ["Boolean", "include_start"],
                ["Boolean", "include_end"],
            ],
            return_type: "ArrayOf(String)",
            method: false,
        },
        {
            name: "buffer_set_line_slice",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start"],
                ["Integer", "end"],
                ["Boolean", "include_start"],
                ["Boolean", "include_end"],
                ["ArrayOf(String)", "replacement"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "buffer_set_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "buffer_del_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "window_set_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "window_del_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "tabpage_set_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Tabpage", "tabpage"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "tabpage_del_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Tabpage", "tabpage"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "vim_set_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "vim_del_var",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "name"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_get_option_info",
            since: 7,
            parameters: [["String", "name"]],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_create_namespace",
            since: 5,
            parameters: [["String", "name"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_get_namespaces",
            since: 5,
            parameters: [],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_buf_get_extmark_by_id",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["Integer", "id"],
                ["Dictionary", "opts"],
            ],
            return_type: "ArrayOf(Integer)",
            method: true,
        },
        {
            name: "nvim_buf_get_extmarks",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["Object", "start"],
                ["Object", "end"],
                ["Dictionary", "opts"],
            ],
            return_type: "Array",
            method: true,
        },
        {
            name: "nvim_buf_set_extmark",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["Integer", "line"],
                ["Integer", "col"],
                ["Dictionary", "opts"],
            ],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_buf_del_extmark",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["Integer", "id"],
            ],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_buf_add_highlight",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["String", "hl_group"],
                ["Integer", "line"],
                ["Integer", "col_start"],
                ["Integer", "col_end"],
            ],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_buf_clear_namespace",
            since: 5,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["Integer", "line_start"],
                ["Integer", "line_end"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_set_decoration_provider",
            since: 7,
            parameters: [
                ["Integer", "ns_id"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_option_value",
            since: 9,
            parameters: [
                ["String", "name"],
                ["Dictionary", "opts"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_set_option_value",
            since: 9,
            parameters: [
                ["String", "name"],
                ["Object", "value"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_all_options_info",
            since: 7,
            parameters: [],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_get_option_info2",
            since: 11,
            parameters: [
                ["String", "name"],
                ["Dictionary", "opts"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_set_option",
            since: 1,
            parameters: [
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_option",
            since: 1,
            parameters: [["String", "name"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_buf_get_option",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "nvim_buf_set_option",
            since: 1,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_get_option",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "nvim_win_set_option",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_tabpage_list_wins",
            since: 1,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "ArrayOf(Window)",
            method: true,
        },
        {
            name: "nvim_tabpage_get_var",
            since: 1,
            parameters: [
                ["Tabpage", "tabpage"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "nvim_tabpage_set_var",
            since: 1,
            parameters: [
                ["Tabpage", "tabpage"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_tabpage_del_var",
            since: 1,
            parameters: [
                ["Tabpage", "tabpage"],
                ["String", "name"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_tabpage_get_win",
            since: 1,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "Window",
            method: true,
        },
        {
            name: "nvim_tabpage_get_number",
            since: 1,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_tabpage_is_valid",
            since: 1,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_ui_attach",
            since: 1,
            parameters: [
                ["Integer", "width"],
                ["Integer", "height"],
                ["Dictionary", "options"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "ui_attach",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Integer", "width"],
                ["Integer", "height"],
                ["Boolean", "enable_rgb"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_ui_set_focus",
            since: 11,
            parameters: [["Boolean", "gained"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_ui_detach",
            since: 1,
            parameters: [],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_ui_try_resize",
            since: 1,
            parameters: [
                ["Integer", "width"],
                ["Integer", "height"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_ui_set_option",
            since: 1,
            parameters: [
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_ui_try_resize_grid",
            since: 6,
            parameters: [
                ["Integer", "grid"],
                ["Integer", "width"],
                ["Integer", "height"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_ui_pum_set_height",
            since: 6,
            parameters: [["Integer", "height"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_ui_pum_set_bounds",
            since: 7,
            parameters: [
                ["Float", "width"],
                ["Float", "height"],
                ["Float", "row"],
                ["Float", "col"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_hl_id_by_name",
            since: 7,
            parameters: [["String", "name"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_get_hl",
            since: 11,
            parameters: [
                ["Integer", "ns_id"],
                ["Dictionary", "opts"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_set_hl",
            since: 7,
            parameters: [
                ["Integer", "ns_id"],
                ["String", "name"],
                ["Dictionary", "val"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_set_hl_ns",
            since: 10,
            parameters: [["Integer", "ns_id"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_set_hl_ns_fast",
            since: 10,
            parameters: [["Integer", "ns_id"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_feedkeys",
            since: 1,
            parameters: [
                ["String", "keys"],
                ["String", "mode"],
                ["Boolean", "escape_ks"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_input",
            since: 1,
            parameters: [["String", "keys"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_input_mouse",
            since: 6,
            parameters: [
                ["String", "button"],
                ["String", "action"],
                ["String", "modifier"],
                ["Integer", "grid"],
                ["Integer", "row"],
                ["Integer", "col"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_replace_termcodes",
            since: 1,
            parameters: [
                ["String", "str"],
                ["Boolean", "from_part"],
                ["Boolean", "do_lt"],
                ["Boolean", "special"],
            ],
            return_type: "String",
            method: false,
        },
        {
            name: "nvim_exec_lua",
            since: 7,
            parameters: [
                ["String", "code"],
                ["Array", "args"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_notify",
            since: 7,
            parameters: [
                ["String", "msg"],
                ["Integer", "log_level"],
                ["Dictionary", "opts"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_strwidth",
            since: 1,
            parameters: [["String", "text"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_list_runtime_paths",
            since: 1,
            parameters: [],
            return_type: "ArrayOf(String)",
            method: false,
        },
        {
            name: "nvim_get_runtime_file",
            since: 7,
            parameters: [
                ["String", "name"],
                ["Boolean", "all"],
            ],
            return_type: "ArrayOf(String)",
            method: false,
        },
        {
            name: "nvim_set_current_dir",
            since: 1,
            parameters: [["String", "dir"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_current_line",
            since: 1,
            parameters: [],
            return_type: "String",
            method: false,
        },
        {
            name: "nvim_set_current_line",
            since: 1,
            parameters: [["String", "line"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_del_current_line",
            since: 1,
            parameters: [],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_var",
            since: 1,
            parameters: [["String", "name"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_set_var",
            since: 1,
            parameters: [
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_del_var",
            since: 1,
            parameters: [["String", "name"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_vvar",
            since: 1,
            parameters: [["String", "name"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_set_vvar",
            since: 6,
            parameters: [
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_echo",
            since: 7,
            parameters: [
                ["Array", "chunks"],
                ["Boolean", "history"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_out_write",
            since: 1,
            parameters: [["String", "str"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_err_write",
            since: 1,
            parameters: [["String", "str"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_err_writeln",
            since: 1,
            parameters: [["String", "str"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_list_bufs",
            since: 1,
            parameters: [],
            return_type: "ArrayOf(Buffer)",
            method: false,
        },
        {
            name: "nvim_get_current_buf",
            since: 1,
            parameters: [],
            return_type: "Buffer",
            method: false,
        },
        {
            name: "nvim_set_current_buf",
            since: 1,
            parameters: [["Buffer", "buffer"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_list_wins",
            since: 1,
            parameters: [],
            return_type: "ArrayOf(Window)",
            method: false,
        },
        {
            name: "nvim_get_current_win",
            since: 1,
            parameters: [],
            return_type: "Window",
            method: false,
        },
        {
            name: "nvim_set_current_win",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_create_buf",
            since: 6,
            parameters: [
                ["Boolean", "listed"],
                ["Boolean", "scratch"],
            ],
            return_type: "Buffer",
            method: false,
        },
        {
            name: "nvim_open_term",
            since: 7,
            parameters: [
                ["Buffer", "buffer"],
                ["Dictionary", "opts"],
            ],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_chan_send",
            since: 7,
            parameters: [
                ["Integer", "chan"],
                ["String", "data"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_list_tabpages",
            since: 1,
            parameters: [],
            return_type: "ArrayOf(Tabpage)",
            method: false,
        },
        {
            name: "nvim_get_current_tabpage",
            since: 1,
            parameters: [],
            return_type: "Tabpage",
            method: false,
        },
        {
            name: "nvim_set_current_tabpage",
            since: 1,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_paste",
            since: 6,
            parameters: [
                ["String", "data"],
                ["Boolean", "crlf"],
                ["Integer", "phase"],
            ],
            return_type: "Boolean",
            method: false,
        },
        {
            name: "nvim_put",
            since: 6,
            parameters: [
                ["ArrayOf(String)", "lines"],
                ["String", "type"],
                ["Boolean", "after"],
                ["Boolean", "follow"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_subscribe",
            since: 1,
            parameters: [["String", "event"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_unsubscribe",
            since: 1,
            parameters: [["String", "event"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_color_by_name",
            since: 1,
            parameters: [["String", "name"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "nvim_get_color_map",
            since: 1,
            parameters: [],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_get_context",
            since: 6,
            parameters: [["Dictionary", "opts"]],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_load_context",
            since: 6,
            parameters: [["Dictionary", "dict"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_get_mode",
            since: 2,
            parameters: [],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_get_keymap",
            since: 3,
            parameters: [["String", "mode"]],
            return_type: "ArrayOf(Dictionary)",
            method: false,
        },
        {
            name: "nvim_set_keymap",
            since: 6,
            parameters: [
                ["String", "mode"],
                ["String", "lhs"],
                ["String", "rhs"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_del_keymap",
            since: 6,
            parameters: [
                ["String", "mode"],
                ["String", "lhs"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_api_info",
            since: 1,
            parameters: [],
            return_type: "Array",
            method: false,
        },
        {
            name: "nvim_set_client_info",
            since: 4,
            parameters: [
                ["String", "name"],
                ["Dictionary", "version"],
                ["String", "type"],
                ["Dictionary", "methods"],
                ["Dictionary", "attributes"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_get_chan_info",
            since: 4,
            parameters: [["Integer", "chan"]],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_list_chans",
            since: 4,
            parameters: [],
            return_type: "Array",
            method: false,
        },
        {
            name: "nvim_call_atomic",
            since: 1,
            parameters: [["Array", "calls"]],
            return_type: "Array",
            method: false,
        },
        {
            name: "nvim_list_uis",
            since: 4,
            parameters: [],
            return_type: "Array",
            method: false,
        },
        {
            name: "nvim_get_proc_children",
            since: 4,
            parameters: [["Integer", "pid"]],
            return_type: "Array",
            method: false,
        },
        {
            name: "nvim_get_proc",
            since: 4,
            parameters: [["Integer", "pid"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_select_popupmenu_item",
            since: 6,
            parameters: [
                ["Integer", "item"],
                ["Boolean", "insert"],
                ["Boolean", "finish"],
                ["Dictionary", "opts"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_del_mark",
            since: 8,
            parameters: [["String", "name"]],
            return_type: "Boolean",
            method: false,
        },
        {
            name: "nvim_get_mark",
            since: 8,
            parameters: [
                ["String", "name"],
                ["Dictionary", "opts"],
            ],
            return_type: "Array",
            method: false,
        },
        {
            name: "nvim_eval_statusline",
            since: 8,
            parameters: [
                ["String", "str"],
                ["Dictionary", "opts"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_exec2",
            since: 11,
            parameters: [
                ["String", "src"],
                ["Dictionary", "opts"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_command",
            since: 1,
            parameters: [["String", "command"]],
            return_type: "void",
            method: false,
        },
        {
            name: "nvim_eval",
            since: 1,
            parameters: [["String", "expr"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_call_function",
            since: 1,
            parameters: [
                ["String", "fn"],
                ["Array", "args"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_call_dict_function",
            since: 4,
            parameters: [
                ["Object", "dict"],
                ["String", "fn"],
                ["Array", "args"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "nvim_parse_expression",
            since: 4,
            parameters: [
                ["String", "expr"],
                ["String", "flags"],
                ["Boolean", "highlight"],
            ],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "nvim_open_win",
            since: 6,
            parameters: [
                ["Buffer", "buffer"],
                ["Boolean", "enter"],
                ["Dictionary", "config"],
            ],
            return_type: "Window",
            method: false,
        },
        {
            name: "nvim_win_set_config",
            since: 6,
            parameters: [
                ["Window", "window"],
                ["Dictionary", "config"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_get_config",
            since: 6,
            parameters: [["Window", "window"]],
            return_type: "Dictionary",
            method: true,
        },
        {
            name: "nvim_win_get_buf",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "Buffer",
            method: true,
        },
        {
            name: "nvim_win_set_buf",
            since: 5,
            parameters: [
                ["Window", "window"],
                ["Buffer", "buffer"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_get_cursor",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "ArrayOf(Integer, 2)",
            method: true,
        },
        {
            name: "nvim_win_set_cursor",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["ArrayOf(Integer, 2)", "pos"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_get_height",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_win_set_height",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["Integer", "height"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_get_width",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_win_set_width",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["Integer", "width"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_get_var",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "nvim_win_set_var",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_del_var",
            since: 1,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_get_position",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "ArrayOf(Integer, 2)",
            method: true,
        },
        {
            name: "nvim_win_get_tabpage",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "Tabpage",
            method: true,
        },
        {
            name: "nvim_win_get_number",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "nvim_win_is_valid",
            since: 1,
            parameters: [["Window", "window"]],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "nvim_win_hide",
            since: 7,
            parameters: [["Window", "window"]],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_close",
            since: 6,
            parameters: [
                ["Window", "window"],
                ["Boolean", "force"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "nvim_win_call",
            since: 7,
            parameters: [
                ["Window", "window"],
                ["LuaRef", "fun"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "nvim_win_set_hl_ns",
            since: 10,
            parameters: [
                ["Window", "window"],
                ["Integer", "ns_id"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "buffer_line_count",
            deprecated_since: 1,
            since: 0,
            parameters: [["Buffer", "buffer"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "buffer_get_lines",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start"],
                ["Integer", "end"],
                ["Boolean", "strict_indexing"],
            ],
            return_type: "ArrayOf(String)",
            method: true,
        },
        {
            name: "buffer_set_lines",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "start"],
                ["Integer", "end"],
                ["Boolean", "strict_indexing"],
                ["ArrayOf(String)", "replacement"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "buffer_get_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "buffer_get_name",
            deprecated_since: 1,
            since: 0,
            parameters: [["Buffer", "buffer"]],
            return_type: "String",
            method: true,
        },
        {
            name: "buffer_set_name",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "buffer_is_valid",
            deprecated_since: 1,
            since: 0,
            parameters: [["Buffer", "buffer"]],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "buffer_get_mark",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "ArrayOf(Integer, 2)",
            method: true,
        },
        {
            name: "vim_command_output",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "command"]],
            return_type: "String",
            method: false,
        },
        {
            name: "buffer_get_number",
            deprecated_since: 1,
            since: 0,
            parameters: [["Buffer", "buffer"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "buffer_clear_highlight",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["Integer", "line_start"],
                ["Integer", "line_end"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "buffer_add_highlight",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["Integer", "ns_id"],
                ["String", "hl_group"],
                ["Integer", "line"],
                ["Integer", "col_start"],
                ["Integer", "col_end"],
            ],
            return_type: "Integer",
            method: true,
        },
        {
            name: "vim_set_option",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_get_option",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "name"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "buffer_get_option",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "buffer_set_option",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Buffer", "buffer"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "window_get_option",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "window_set_option",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
                ["Object", "value"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "tabpage_get_windows",
            deprecated_since: 1,
            since: 0,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "ArrayOf(Window)",
            method: true,
        },
        {
            name: "tabpage_get_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Tabpage", "tabpage"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "tabpage_get_window",
            deprecated_since: 1,
            since: 0,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "Window",
            method: true,
        },
        {
            name: "tabpage_is_valid",
            deprecated_since: 1,
            since: 0,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "Boolean",
            method: true,
        },
        {
            name: "ui_detach",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "void",
            method: false,
        },
        {
            name: "ui_try_resize",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Integer", "width"],
                ["Integer", "height"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "vim_feedkeys",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["String", "keys"],
                ["String", "mode"],
                ["Boolean", "escape_ks"],
            ],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_input",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "keys"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "vim_replace_termcodes",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["String", "str"],
                ["Boolean", "from_part"],
                ["Boolean", "do_lt"],
                ["Boolean", "special"],
            ],
            return_type: "String",
            method: false,
        },
        {
            name: "vim_strwidth",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "text"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "vim_list_runtime_paths",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "ArrayOf(String)",
            method: false,
        },
        {
            name: "vim_change_directory",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "dir"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_get_current_line",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "String",
            method: false,
        },
        {
            name: "vim_set_current_line",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "line"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_del_current_line",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_get_var",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "name"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "vim_get_vvar",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "name"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "vim_out_write",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "str"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_err_write",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "str"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_report_error",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "str"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_get_buffers",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "ArrayOf(Buffer)",
            method: false,
        },
        {
            name: "vim_get_current_buffer",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "Buffer",
            method: false,
        },
        {
            name: "vim_set_current_buffer",
            deprecated_since: 1,
            since: 0,
            parameters: [["Buffer", "buffer"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_get_windows",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "ArrayOf(Window)",
            method: false,
        },
        {
            name: "vim_get_current_window",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "Window",
            method: false,
        },
        {
            name: "vim_set_current_window",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_get_tabpages",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "ArrayOf(Tabpage)",
            method: false,
        },
        {
            name: "vim_get_current_tabpage",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "Tabpage",
            method: false,
        },
        {
            name: "vim_set_current_tabpage",
            deprecated_since: 1,
            since: 0,
            parameters: [["Tabpage", "tabpage"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_subscribe",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "event"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_unsubscribe",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "event"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_name_to_color",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "name"]],
            return_type: "Integer",
            method: false,
        },
        {
            name: "vim_get_color_map",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "Dictionary",
            method: false,
        },
        {
            name: "vim_get_api_info",
            deprecated_since: 1,
            since: 0,
            parameters: [],
            return_type: "Array",
            method: false,
        },
        {
            name: "vim_command",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "command"]],
            return_type: "void",
            method: false,
        },
        {
            name: "vim_eval",
            deprecated_since: 1,
            since: 0,
            parameters: [["String", "expr"]],
            return_type: "Object",
            method: false,
        },
        {
            name: "vim_call_function",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["String", "fn"],
                ["Array", "args"],
            ],
            return_type: "Object",
            method: false,
        },
        {
            name: "window_get_buffer",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "Buffer",
            method: true,
        },
        {
            name: "window_get_cursor",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "ArrayOf(Integer, 2)",
            method: true,
        },
        {
            name: "window_set_cursor",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["ArrayOf(Integer, 2)", "pos"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "window_get_height",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "window_set_height",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["Integer", "height"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "window_get_width",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "Integer",
            method: true,
        },
        {
            name: "window_set_width",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["Integer", "width"],
            ],
            return_type: "void",
            method: true,
        },
        {
            name: "window_get_var",
            deprecated_since: 1,
            since: 0,
            parameters: [
                ["Window", "window"],
                ["String", "name"],
            ],
            return_type: "Object",
            method: true,
        },
        {
            name: "window_get_position",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "ArrayOf(Integer, 2)",
            method: true,
        },
        {
            name: "window_get_tabpage",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "Tabpage",
            method: true,
        },
        {
            name: "window_is_valid",
            deprecated_since: 1,
            since: 0,
            parameters: [["Window", "window"]],
            return_type: "Boolean",
            method: true,
        },
    ],
    ui_events: [
        {
            name: "mode_info_set",
            parameters: [
                ["Boolean", "enabled"],
                ["Array", "cursor_styles"],
            ],
            since: 3,
        },
        { name: "update_menu", parameters: [], since: 3 },
        { name: "busy_start", parameters: [], since: 3 },
        { name: "busy_stop", parameters: [], since: 3 },
        { name: "mouse_on", parameters: [], since: 3 },
        { name: "mouse_off", parameters: [], since: 3 },
        {
            name: "mode_change",
            parameters: [
                ["String", "mode"],
                ["Integer", "mode_idx"],
            ],
            since: 3,
        },
        { name: "bell", parameters: [], since: 3 },
        { name: "visual_bell", parameters: [], since: 3 },
        { name: "flush", parameters: [], since: 3 },
        { name: "suspend", parameters: [], since: 3 },
        { name: "set_title", parameters: [["String", "title"]], since: 3 },
        { name: "set_icon", parameters: [["String", "icon"]], since: 3 },
        { name: "screenshot", parameters: [["String", "path"]], since: 7 },
        {
            name: "option_set",
            parameters: [
                ["String", "name"],
                ["Object", "value"],
            ],
            since: 4,
        },
        { name: "update_fg", parameters: [["Integer", "fg"]], since: 3 },
        { name: "update_bg", parameters: [["Integer", "bg"]], since: 3 },
        { name: "update_sp", parameters: [["Integer", "sp"]], since: 3 },
        {
            name: "resize",
            parameters: [
                ["Integer", "width"],
                ["Integer", "height"],
            ],
            since: 3,
        },
        { name: "clear", parameters: [], since: 3 },
        { name: "eol_clear", parameters: [], since: 3 },
        {
            name: "cursor_goto",
            parameters: [
                ["Integer", "row"],
                ["Integer", "col"],
            ],
            since: 3,
        },
        { name: "highlight_set", parameters: [["Dictionary", "attrs"]], since: 3 },
        { name: "put", parameters: [["String", "str"]], since: 3 },
        {
            name: "set_scroll_region",
            parameters: [
                ["Integer", "top"],
                ["Integer", "bot"],
                ["Integer", "left"],
                ["Integer", "right"],
            ],
            since: 3,
        },
        { name: "scroll", parameters: [["Integer", "count"]], since: 3 },
        {
            name: "default_colors_set",
            parameters: [
                ["Integer", "rgb_fg"],
                ["Integer", "rgb_bg"],
                ["Integer", "rgb_sp"],
                ["Integer", "cterm_fg"],
                ["Integer", "cterm_bg"],
            ],
            since: 4,
        },
        {
            name: "hl_attr_define",
            parameters: [
                ["Integer", "id"],
                ["Dictionary", "rgb_attrs"],
                ["Dictionary", "cterm_attrs"],
                ["Array", "info"],
            ],
            since: 5,
        },
        {
            name: "hl_group_set",
            parameters: [
                ["String", "name"],
                ["Integer", "id"],
            ],
            since: 6,
        },
        {
            name: "grid_resize",
            parameters: [
                ["Integer", "grid"],
                ["Integer", "width"],
                ["Integer", "height"],
            ],
            since: 5,
        },
        { name: "grid_clear", parameters: [["Integer", "grid"]], since: 5 },
        {
            name: "grid_cursor_goto",
            parameters: [
                ["Integer", "grid"],
                ["Integer", "row"],
                ["Integer", "col"],
            ],
            since: 5,
        },
        {
            name: "grid_line",
            parameters: [
                ["Integer", "grid"],
                ["Integer", "row"],
                ["Integer", "col_start"],
                ["Array", "data"],
            ],
            since: 5,
        },
        {
            name: "grid_scroll",
            parameters: [
                ["Integer", "grid"],
                ["Integer", "top"],
                ["Integer", "bot"],
                ["Integer", "left"],
                ["Integer", "right"],
                ["Integer", "rows"],
                ["Integer", "cols"],
            ],
            since: 5,
        },
        { name: "grid_destroy", parameters: [["Integer", "grid"]], since: 6 },
        {
            name: "win_pos",
            parameters: [
                ["Integer", "grid"],
                ["Window", "win"],
                ["Integer", "startrow"],
                ["Integer", "startcol"],
                ["Integer", "width"],
                ["Integer", "height"],
            ],
            since: 6,
        },
        {
            name: "win_float_pos",
            parameters: [
                ["Integer", "grid"],
                ["Window", "win"],
                ["String", "anchor"],
                ["Integer", "anchor_grid"],
                ["Float", "anchor_row"],
                ["Float", "anchor_col"],
                ["Boolean", "focusable"],
                ["Integer", "zindex"],
            ],
            since: 6,
        },
        {
            name: "win_external_pos",
            parameters: [
                ["Integer", "grid"],
                ["Window", "win"],
            ],
            since: 6,
        },
        { name: "win_hide", parameters: [["Integer", "grid"]], since: 6 },
        { name: "win_close", parameters: [["Integer", "grid"]], since: 6 },
        {
            name: "msg_set_pos",
            parameters: [
                ["Integer", "grid"],
                ["Integer", "row"],
                ["Boolean", "scrolled"],
                ["String", "sep_char"],
            ],
            since: 6,
        },
        {
            name: "win_viewport",
            parameters: [
                ["Integer", "grid"],
                ["Window", "win"],
                ["Integer", "topline"],
                ["Integer", "botline"],
                ["Integer", "curline"],
                ["Integer", "curcol"],
                ["Integer", "line_count"],
                ["Integer", "scroll_delta"],
            ],
            since: 7,
        },
        {
            name: "win_extmark",
            parameters: [
                ["Integer", "grid"],
                ["Window", "win"],
                ["Integer", "ns_id"],
                ["Integer", "mark_id"],
                ["Integer", "row"],
                ["Integer", "col"],
            ],
            since: 10,
        },
        {
            name: "popupmenu_show",
            parameters: [
                ["Array", "items"],
                ["Integer", "selected"],
                ["Integer", "row"],
                ["Integer", "col"],
                ["Integer", "grid"],
            ],
            since: 3,
        },
        { name: "popupmenu_hide", parameters: [], since: 3 },
        { name: "popupmenu_select", parameters: [["Integer", "selected"]], since: 3 },
        {
            name: "tabline_update",
            parameters: [
                ["Tabpage", "current"],
                ["Array", "tabs"],
                ["Buffer", "current_buffer"],
                ["Array", "buffers"],
            ],
            since: 3,
        },
        {
            name: "cmdline_show",
            parameters: [
                ["Array", "content"],
                ["Integer", "pos"],
                ["String", "firstc"],
                ["String", "prompt"],
                ["Integer", "indent"],
                ["Integer", "level"],
            ],
            since: 3,
        },
        {
            name: "cmdline_pos",
            parameters: [
                ["Integer", "pos"],
                ["Integer", "level"],
            ],
            since: 3,
        },
        {
            name: "cmdline_special_char",
            parameters: [
                ["String", "c"],
                ["Boolean", "shift"],
                ["Integer", "level"],
            ],
            since: 3,
        },
        { name: "cmdline_hide", parameters: [["Integer", "level"]], since: 3 },
        { name: "cmdline_block_show", parameters: [["Array", "lines"]], since: 3 },
        { name: "cmdline_block_append", parameters: [["Array", "lines"]], since: 3 },
        { name: "cmdline_block_hide", parameters: [], since: 3 },
        { name: "wildmenu_show", parameters: [["Array", "items"]], since: 3 },
        { name: "wildmenu_select", parameters: [["Integer", "selected"]], since: 3 },
        { name: "wildmenu_hide", parameters: [], since: 3 },
        {
            name: "msg_show",
            parameters: [
                ["String", "kind"],
                ["Array", "content"],
                ["Boolean", "replace_last"],
            ],
            since: 6,
        },
        { name: "msg_clear", parameters: [], since: 6 },
        { name: "msg_showcmd", parameters: [["Array", "content"]], since: 6 },
        { name: "msg_showmode", parameters: [["Array", "content"]], since: 6 },
        { name: "msg_ruler", parameters: [["Array", "content"]], since: 6 },
        { name: "msg_history_show", parameters: [["Array", "entries"]], since: 6 },
        { name: "msg_history_clear", parameters: [], since: 10 },
    ],
    ui_options: [
        "rgb",
        "ext_cmdline",
        "ext_popupmenu",
        "ext_tabline",
        "ext_wildmenu",
        "ext_messages",
        "ext_linegrid",
        "ext_multigrid",
        "ext_hlstate",
        "ext_termcolors",
    ],
    error_types: { Exception: { id: 0 }, Validation: { id: 1 } },
    types: {
        Buffer: { id: 0, prefix: "nvim_buf_" },
        Window: { id: 1, prefix: "nvim_win_" },
        Tabpage: { id: 2, prefix: "nvim_tabpage_" },
    },
} as const;
