name: Release
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --no-save
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bun run commitlint --from=origin/main --to=HEAD
      - name: Validate code formatting
        run: |
          bun run format
          if [[ $(git status --porcelain) ]]; then
            echo "Code not properly formatted. Please run 'bun run format' locally and commit changes."
            exit 1
          fi
      - name: Validate tailwind.css
        run: |
          bun run tailwind:compile
          if [[ $(git status --porcelain) ]]; then
            echo "Outdated tailwind.css found. Please run 'bun run tailwind:compile' locally and commit changes."
            exit 1
          fi
      - name: Lint & check types
        run: bun run lint
      - name: Test
        run: bun test

  Release:
    needs: [Test]
    permissions:
      contents: write
      issues: write
    if: |
      github.ref == 'refs/heads/main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run semantic-release
